"""Project Building Area Operations."""

import copy
from typing import Any

from src.components.building_area import BuildingAreaListManager
from src.types.core_types import WholeBldgUse


# TODO: building area key is uuid, which should be generated by the data manager,
# and the WholeBldgUse type set the key as required. need to add a type without key.
def add_building_area_to_project(
    project: dict[str, Any], new_building_area: WholeBldgUse
) -> dict[str, Any]:
    """Add a new building area to the project using buildingAreaListManager.

    Args:
        project: The project object to modify
        new_building_area: The building area object to add

    Returns:
        Updated project object with the building area added

    Raises:
        ValueError: If building area (wholeBldgUse) array not found in project.
    """
    # Deep clone to avoid mutating the original project
    updated_project = copy.deepcopy(project)

    if (
        "lighting" in updated_project
        and isinstance(updated_project["lighting"], dict)
        and "wholeBldgUse" in updated_project["lighting"]
        and isinstance(updated_project["lighting"]["wholeBldgUse"], list)
    ):
        manager = BuildingAreaListManager(updated_project["lighting"]["wholeBldgUse"])
        updated_project["lighting"]["wholeBldgUse"] = manager.add_new(new_building_area)
    else:
        raise ValueError("building area (wholeBldgUse) array not found in project.")

    return updated_project
