"""Default project template used to bootstrap new COMcheck projects.

The :data:`PROJECT_TEMPLATE` constant is a fully validated :class:`ComBuilding`
instance pre-populated with sensible defaults for all required sections
(envelope, lighting, HVAC, location, etc.).
"""

from comcheck_api.types.core_types import ComBuilding

PROJECT_TEMPLATE = ComBuilding.model_validate(
    {
        "control": {
            "code": "CEZ_IECC2018",
            "complianceMode": "UA",
            "version": "",
        },
        "envelope": {
            "useVltDetails": False,
            "useCoolRoofPerformanceDetails": False,
            "postAltWindowWallPct": None,
            "postAltSkylightRoofPct": None,
            "altPctGlazingAreaReplaced": None,
            "altPctSkylightAreaReplaced": None,
            "applyWindowPctAllowanceForDaylighting": False,
            "applySkylightPctAllowanceForDaylighting": False,
            "agWall": [],
            "bgWall": [],
            "roof": [],
            "floor": [],
            "door": [],
            "window": [],
            "skylight": [],
            "useOrientDetails": True,
            "airBarrierComplianceType": "AIR_BARRIER_OPTION_UNKNOWN",
        },
        "project": {
            "projectTitle": "Default Project",
            "projectPermitNumber": "",
            "projectPermitDate": "",
            "projectTaxMap": None,
            "projectLotNumber": None,
            "projectAddress": "",
            "projectAddress2": None,
            "projectCity": "",
            "projectState": "",
            "projectZipCode": "",
            "projectComplete": None,
            "ownerFirstName": "",
            "ownerLastName": "",
            "ownerCompany": "",
            "ownerAddress": "",
            "ownerAddress2": None,
            "ownerCity": "",
            "ownerState": "",
            "ownerZipCode": "",
            "ownerPhone": "",
            "ownerEmail": "",
            "developerFirstName": "",
            "developerLastName": "",
            "developerCompany": "",
            "developerAddress": "",
            "developerAddress2": None,
            "developerCity": "",
            "developerState": "",
            "developerZipCode": "",
            "developerPhone": "",
            "developerEmail": "",
            "notes": "",
        },
        "lighting": {
            "exteriorLightingZoneType": "EXT_ZONE_UNSPECIFIED",
            "exteriorUse": [],
            "wholeBldgUse": [],
            "fixtureSchedule": [],
        },
        "renewable": {
            "renewableException": "RENEWABLE_ONSITE_EXCEPTION_NONE",
            "numberOfFloors": 1,
            "largestThreeFloorArea": 0,
            "requiredCapacity": 0,
            "proposedCapacity": 0,
            "roofAreaForRenewable": 0,
            "requiredOffsiteRenewableEnergy": 0,
            "proposedOffsiteRenewableEnergy": 0,
            "renewableSystem": [],
            "offsiteRenewableProcurement": [],
        },
        "location": {"state": "Colorado", "city": "Boulder", "climateZone": 5},
        "semiheated": None,
        "hvac": {"hvacPlant": [], "hvacSystem": [], "fanSystem": []},
        "swhSystem": [],
        "requirements": [],
        "isNonresidentialConditioning": True,
        "isResidentialConditioning": False,
        "isSemiheatedConditioning": False,
        "isHistoricBuilding": False,
        "feetBldgHeight": None,
        "constructionType": "NONE",
        "projectType": "NEW_CONSTRUCTION",
        "projectSubType": "CONSTRUCTION_COMPLETE",
        "projectMechanicalType": "PROJECT_HVAC_WITH_CENTRAL",
        "projectCoreAndShellCredit": 0,
        "efficiencyPackages": [],
        "performanceRating": 0,
        "energyCreditPerformanceRating": 0,
        "buildingUseType": "ACTIVITY",
        "conditioningType": "HEATING_AND_COOLING",
        "heatingFuelType": "UNKNOWN_FUEL",
        "userProject": None,
        "allElectric": None,
        "isRenewable": None,
        "hasBattery": None,
        "hasCharger": None,
        "hasHeatPump": None,
    }
)
