"""Project Building Area Operations."""

from typing import Any

from comcheck_api.components.building_area import BuildingAreaListManager
from comcheck_api.types.core_types import ComBuilding, WholeBldgUse


# TODO: building area key is uuid, which should be generated by the data manager,
# and the WholeBldgUse type set the key as required. need to add a type without key.
def add_building_area_to_project(
    project: ComBuilding, new_building_area: WholeBldgUse
) -> ComBuilding:
    """Add a new building area to the project using buildingAreaListManager.

    Args:
        project: The project object to modify
        new_building_area: The building area object to add

    Returns:
        Updated project object with the building area added

    Raises:
        ValueError: If building area (wholeBldgUse) array not found in project.
    """

    updated_project = project.model_copy(deep=True)
    updated_project.lighting.add_subcomponent(new_building_area)

    return updated_project
