repos:
  - repo: https://github.com/psf/black
    rev: 26.1.0  # latest Black release
    hooks:
      - id: black
        language_version: python3
        exclude: ^comcheck_api/types/core_types\.py$

