from comcheck_api.types.core_types import Envelope, WholeBldgUse

TEST_PROJECT_ENVELOPE = Envelope(
    **{
        "id": 13943,
        "useVltDetails": True,
        "useCoolRoofPerformanceDetails": False,
        "postAltWindowWallPct": None,
        "postAltSkylightRoofPct": None,
        "altPctGlazingAreaReplaced": None,
        "altPctSkylightAreaReplaced": None,
        "applyWindowPctAllowanceForDaylighting": False,
        "applySkylightPctAllowanceForDaylighting": False,
        "agWall": [
            {
                "id": 43498,
                "cavityRValue": 20,
                "continuousRValue": 10,
                "propUValue": 0.048,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Ext Wall:Exterior Wall 1",
                "grossArea": 4800,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "NORTH",
                "window": [
                    {
                        "id": 41068,
                        "cavityRValue": 0,
                        "continuousRValue": 0,
                        "propUValue": 0.55,
                        "altExemptType": None,
                        "description": "",
                        "assemblyType": "Window:Window",
                        "grossArea": 300,
                        "propShgc": 0.5,
                        "propProjectionFactor": 2,
                        "glazingType": "TRIPLE_PANE",
                        "bldgUseKey": "70084399",
                        "adjacentSpaceType": None,
                        "allowanceType": None,
                        "constructionType": None,
                        "exemptionType": None,
                        "orientation": "UNSPECIFIED_ORIENTATION",
                        "propVt": 0,
                        "preAltPropShgc": 0,
                        "solarType": "CLEAR",
                        "glazingMaterialType": None,
                        "productType": None,
                        "isSiteShading": None,
                        "perfDataType": "PERF_TYPE_DEFAULT",
                        "productId": None,
                        "frameType": "METAL",
                        "windowOpenType": "NON_OPERABLE_WINDOW",
                    }
                ],
                "door": [
                    {
                        "id": 31317,
                        "cavityRValue": 0,
                        "continuousRValue": 0,
                        "propUValue": 0.37,
                        "altExemptType": None,
                        "description": "",
                        "assemblyType": "Door:Door",
                        "grossArea": 23,
                        "propShgc": 0,
                        "propProjectionFactor": 0,
                        "glazingType": None,
                        "bldgUseKey": "70084399",
                        "adjacentSpaceType": None,
                        "allowanceType": None,
                        "constructionType": None,
                        "exemptionType": None,
                        "orientation": "UNSPECIFIED_ORIENTATION",
                        "propVt": 0,
                        "preAltPropShgc": 0,
                        "solarType": None,
                        "glazingMaterialType": None,
                        "productType": None,
                        "isSiteShading": None,
                        "perfDataType": None,
                        "productId": None,
                        "frameType": None,
                        "doorType": "INSUL_METAL_DOOR",
                        "doorOpenType": "SWINGING_DOOR",
                        "doorEntranceType": "ENTRANCE_DOOR",
                    }
                ],
                "insulationPosition": None,
                "cmuType": None,
                "concreteDensity": 0,
                "concreteThickness": 0,
                "furringType": None,
                "heatCapacity": 0,
                "wallType": "METAL_FRAME_24_AG_WALL",
                "agWallConstructionDetailsType": "NONE",
                "agWallExteriorFinishDetailsType": None,
                "continuousRDerateFactor": None,
                "otherWallType": "NONE",
                "thermalBridgeExceptionType": "THERMAL_BRIDGE_EXCEPTION_NONE",
                "thermalBridge": [],
                "effectiveUFactor": 0.054,
            },
            {
                "id": 43499,
                "cavityRValue": 20,
                "continuousRValue": 10,
                "propUValue": 0.048,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Ext Wall:Exterior Wall 3",
                "grossArea": 4800,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "SOUTH",
                "window": [],
                "door": [],
                "insulationPosition": None,
                "cmuType": None,
                "concreteDensity": 0,
                "concreteThickness": 0,
                "furringType": None,
                "heatCapacity": 0,
                "wallType": "METAL_FRAME_24_AG_WALL",
                "agWallConstructionDetailsType": "NONE",
                "agWallExteriorFinishDetailsType": None,
                "continuousRDerateFactor": None,
                "otherWallType": "NONE",
                "thermalBridgeExceptionType": "THERMAL_BRIDGE_EXCEPTION_NONE",
                "thermalBridge": [],
                "effectiveUFactor": 0.052,
            },
            {
                "id": 43500,
                "cavityRValue": 20,
                "continuousRValue": 10,
                "propUValue": 0.048,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Ext Wall:Exterior Wall 2",
                "grossArea": 2880,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "EAST",
                "window": [],
                "door": [],
                "insulationPosition": None,
                "cmuType": None,
                "concreteDensity": 0,
                "concreteThickness": 0,
                "furringType": None,
                "heatCapacity": 0,
                "wallType": "METAL_FRAME_24_AG_WALL",
                "agWallConstructionDetailsType": "NONE",
                "agWallExteriorFinishDetailsType": None,
                "continuousRDerateFactor": None,
                "otherWallType": "NONE",
                "thermalBridgeExceptionType": "THERMAL_BRIDGE_EXCEPTION_NONE",
                "thermalBridge": [],
                "effectiveUFactor": 0.05,
            },
            {
                "id": 43501,
                "cavityRValue": 20,
                "continuousRValue": 10,
                "propUValue": 0.048,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Ext Wall:Exterior Wall 4",
                "grossArea": 2880,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "WEST",
                "window": [],
                "door": [],
                "insulationPosition": None,
                "cmuType": None,
                "concreteDensity": 0,
                "concreteThickness": 0,
                "furringType": None,
                "heatCapacity": 0,
                "wallType": "METAL_FRAME_24_AG_WALL",
                "agWallConstructionDetailsType": "NONE",
                "agWallExteriorFinishDetailsType": None,
                "continuousRDerateFactor": None,
                "otherWallType": "NONE",
                "thermalBridgeExceptionType": "THERMAL_BRIDGE_EXCEPTION_NONE",
                "thermalBridge": [],
                "effectiveUFactor": 0.05,
            },
        ],
        "bgWall": [],
        "roof": [
            {
                "id": 10185,
                "cavityRValue": 0,
                "continuousRValue": 37,
                "propUValue": 0.026,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Roof:Roof",
                "grossArea": 6000,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "UNSPECIFIED_ORIENTATION",
                "roofType": "ABOVE_DECK_ROOF",
                "skylight": [
                    {
                        "id": 1963,
                        "cavityRValue": 0,
                        "continuousRValue": 0,
                        "propUValue": 0.55,
                        "altExemptType": None,
                        "description": "",
                        "assemblyType": "Skylight:Skylight",
                        "grossArea": 100,
                        "propShgc": 0.6,
                        "propProjectionFactor": 0,
                        "glazingType": "DOUBLE_PANE_LOWE",
                        "bldgUseKey": "70084399",
                        "adjacentSpaceType": None,
                        "allowanceType": None,
                        "constructionType": None,
                        "exemptionType": None,
                        "orientation": "UNSPECIFIED_ORIENTATION",
                        "propVt": 0,
                        "preAltPropShgc": 0,
                        "solarType": "TINTED",
                        "glazingMaterialType": "GLASS_GLAZING_MAT",
                        "productType": None,
                        "isSiteShading": None,
                        "perfDataType": "PERF_TYPE_DEFAULT",
                        "productId": None,
                        "frameType": "METAL",
                        "curbType": "NO_CURB_SKYLIGHT",
                    }
                ],
                "highAlbedoRoofReqType": "HA_ROOF_EXEMPTION_VEGETATED",
                "highAlbedoRoofType": None,
                "otherRoofType": None,
                "purlinSpacing": 0,
                "roofInsulType": None,
                "solarReflectance": 0,
                "solarReflectanceIndex": 0,
                "thermalEmittance": 0,
            }
        ],
        "floor": [
            {
                "id": 8824,
                "cavityRValue": 0,
                "continuousRValue": 15,
                "propUValue": 0.72,
                "altExemptType": None,
                "description": "",
                "assemblyType": "Floor:Floor",
                "grossArea": 320,
                "bldgUseKey": "70084399",
                "adjacentSpaceType": None,
                "allowanceType": None,
                "constructionType": None,
                "exemptionType": None,
                "orientation": "UNSPECIFIED_ORIENTATION",
                "floorType": "HEATED_SLAB_ON_GRADE",
                "depthOfInsulation": 4,
                "floorExposedFrameType": None,
                "hasEdgeInsul": None,
                "insulationPosition": "VERTICAL",
                "slabFullInsulBelowMinRValue": 0,
            }
        ],
        "door": [],
        "window": [],
        "skylight": [],
        "useOrientDetails": True,
        "airBarrierComplianceType": "AIR_BARRIER_OPTION_UNKNOWN",
    }
)

TEST_BUILDING_AREA = [
    WholeBldgUse(
        **{
            "id": 45738,
            "lightingId": 13940,
            "key": "70084399",
            "wholeBldgType": "WHOLE_BUILDING_OFFICE",
            "areaDescription": "Office",
            "constructionType": "NON_RESIDENTIAL",
            "floorArea": 100000,
            "internalLoad": 0,
            "powerDensity": 0.62,
            "isTenantSpace": False,
            "interiorLightingSpace": {
                "altExemptType": "EXEMPT_NOT_SET",
                "preAltNumberFixtures": 0,
                "preAltTotalWattage": 0,
                "numFixturesAlteredOrAdded": 0,
                "postAltTotalWattage": 0,
                "fixture": [],
            },
            "activityUse": [
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93066,
                    "activityType": "ACTIVITY_COMMON_OFFICE_ENCLOSED",
                    "areaDescription": "Office Cabins",
                    "ceilingHeight": 0,
                    "floorArea": 1000,
                    "internalLoad": 1.95,
                    "powerDensity": 0.73,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244585,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165604,
                                "scheduleFixtureKey": "06c0f679-fd6f-4768-b43b-4520ff5dd599",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Suspended Linear LED Fixture",
                                "exemptionType": None,
                                "fixtureType": "Suspended Linear LED Fixture",
                                "fixtureWattage": 10,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "LED",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 40,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 400,
                    "allowedWattage": 730,
                },
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93067,
                    "activityType": "ACTIVITY_COMMON_OFFICE_ENCLOSED_GT250",
                    "areaDescription": "Office Cubicles",
                    "ceilingHeight": 0,
                    "floorArea": 6000,
                    "internalLoad": 1.95,
                    "powerDensity": 0.66,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244586,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165603,
                                "scheduleFixtureKey": "bd2afb1e-01b7-43a4-91f6-d3fd2a893f10",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Recessed LED Troffer",
                                "exemptionType": None,
                                "fixtureType": "Recessed LED Troffer",
                                "fixtureWattage": 12,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "LED",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 200,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 2400,
                    "allowedWattage": 3960,
                },
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93068,
                    "activityType": "ACTIVITY_COMMON_CORRIDOR_LT_8_FEET",
                    "areaDescription": "Corridors",
                    "ceilingHeight": 0,
                    "floorArea": 500,
                    "internalLoad": 1.95,
                    "powerDensity": 0.44,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244587,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165607,
                                "scheduleFixtureKey": "8d31188c-5065-40e8-bcdf-644ccea49bac",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Entrance LED Light",
                                "exemptionType": None,
                                "fixtureType": "LED PAR",
                                "fixtureWattage": 7,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "LED",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 50,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 350,
                    "allowedWattage": 220,
                },
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93069,
                    "activityType": "ACTIVITY_COMMON_COPY_PRINT_ROOM",
                    "areaDescription": "Print Room",
                    "ceilingHeight": 0,
                    "floorArea": 50,
                    "internalLoad": 1.95,
                    "powerDensity": 0.56,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244590,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165608,
                                "scheduleFixtureKey": "6b5db100-b338-4ade-a79c-829e76d9e51c",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Compact Fluorescent Fixture",
                                "exemptionType": None,
                                "fixtureType": "Compact Fluorescent Fixture",
                                "fixtureWattage": 20,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "COMP_FLUOR",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 2,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 40,
                    "allowedWattage": 28,
                },
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93070,
                    "activityType": "ACTIVITY_COMMON_CONFERENCE_HALL",
                    "areaDescription": "Conference rooms",
                    "ceilingHeight": 0,
                    "floorArea": 6000,
                    "internalLoad": 1.95,
                    "powerDensity": 0.88,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244589,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165605,
                                "scheduleFixtureKey": "8d31188c-5065-40e8-bcdf-644ccea49bac",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Entrance LED Light",
                                "exemptionType": None,
                                "fixtureType": "LED PAR",
                                "fixtureWattage": 7,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "LED",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 200,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 1400,
                    "allowedWattage": 5280,
                },
                {
                    "constructionType": "NON_RESIDENTIAL",
                    "id": 93071,
                    "activityType": "ACTIVITY_COMMON_FOOD_PREP",
                    "areaDescription": "Kitchen",
                    "ceilingHeight": 0,
                    "floorArea": 200,
                    "internalLoad": 1.95,
                    "powerDensity": 1.19,
                    "roomCavityRatioThreshold": None,
                    "isUnfinishedSpace": None,
                    "key": "70084399",
                    "interiorLightingSpace": {
                        "id": 244588,
                        "altExemptType": None,
                        "description": "spaceIntspace",
                        "listPosition": None,
                        "numFixturesAlteredOrAdded": 0,
                        "postAltTotalWattage": 0,
                        "preAltNumberFixtures": 0,
                        "preAltTotalWattage": 0,
                        "allowanceType": None,
                        "exemptionType": None,
                        "allowanceFloorArea": 0,
                        "rcrFloorToWorkplaneHeight": 0,
                        "rcrPerimeter": 0,
                        "rcrWorkplaneToLuminaireHeight": 0,
                        "fixture": [
                            {
                                "id": 165606,
                                "scheduleFixtureKey": "06c0f679-fd6f-4768-b43b-4520ff5dd599",
                                "allowanceType": None,
                                "ballast": None,
                                "description": "Suspended Linear LED Fixture",
                                "exemptionType": None,
                                "fixtureType": "Suspended Linear LED Fixture",
                                "fixtureWattage": 10,
                                "allowanceFloorArea": 0,
                                "lampType": "NONE",
                                "lightingType": "LED",
                                "listPosition": None,
                                "numberOfLamps": None,
                                "powerAllowance": 0,
                                "quantity": 10,
                                "trackCircuitBreakerAmps": 0,
                                "trackCircuitBreakerVolts": 0,
                                "trackCurrentLimiterWattage": 0,
                                "trackLength": 0,
                                "trackLightingWattageBasisType": None,
                                "trackTotalLuminaireWattage": 0,
                                "trackTransformerWattage": 0,
                                "typeOfFixture": "",
                                "advControlsAllowanceAperture": 0,
                                "advControlsAllowanceType": None,
                                "quantityWithAdvControls": 0,
                                "lightingControl": [],
                            }
                        ],
                    },
                    "proposedWattage": 100,
                    "allowedWattage": 238,
                },
            ],
        }
    )
]
